### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/state-of-css-2019#1]
Some general feedback

- [x] I think we should default to using percentages for everything, it's more meaningful as people might now know how many total respondents there were. We can then add a toggle for each chart if we need to. 
- [x] font for horizontal chart legends is wrong.

**Comment by plouc** [comment]
I mostly agree about percentages, however in some case, it's not desirable and not really feasible, for example if we take `Other Tools > Browsers`, we should use percentage for the bar chart displaying original options, however for the `other` choice, I think we should use counts as if we use percentages, value will be too small to be noticeable or event appear on the chart.

**Comment by plouc** [comment]
What do you mean by:
> font for horizontal chart legends is wrong.
?
