### ISSUE TITLE
[demographics] Source Breakdown

### ISSUE THREAD

**Issue by plouc** [StateOfJS/state-of-css-2019#19]

**Comment by plouc** [comment]
@SachaG, I've pushed this block, maybe you can check and close this issue if it's OK.
Also, I didn't used a waffle chart but an horizontal bar block to be able to show more sources.

**Comment by SachaG** [comment]
- email/newsletter/stateofjs: are they all the same thing? how do we detect email and newsletter?
- work: replace by "word of mouth" and merge with "friends"? 
- medium/freeCodeCamp: same thing?

**Comment by SachaG** [comment]
Also:

- where do the source names come from? how can we format them better?

**Comment by plouc** [comment]
You can review the normalisation config [here](https://github.com/StateOfJS/data-tools/blob/master/conf/base.yaml#L1086), it contains rules and source names.
