### ISSUE TITLE
Horizontal/Vertical bar units selector

### ISSUE THREAD

**Issue by plouc** [StateOfJS/state-of-css-2019#22]
- [x] adjust ticks count when count is used instead of percentage
- [x] do not display count twice in the tooltip, when count is used
- [x] disable animation
- [x] improve button style
- [ ] put button before the chart, not before the legends?

**Comment by SachaG** [comment]
I actually thought the animation looked cool :)

**Comment by plouc** [comment]
It's weird as the bars should remain the same, we just change the display, the proportions are identical.

**Comment by plouc** [comment]
But if you prefer to keep it, no problem :)

**Comment by plouc** [comment]
We'll decide later if we keep the toggle before the legends
