### ISSUE TITLE
Incorrect share links

### ISSUE THREAD

**Issue by daanhaitsma** [StateOfJS/state-of-css-2019#35]
Being a huge fan of Tailwind, I was quite surprised by the amount of people who weren't (_"I've HEARD of it, and am NOT interested"_)

After sharing the link to the results (https://2019.stateofcss.com/technologies/css-frameworks/tailwind), I noticed it gave a 404 error. Adding an octothorpe does make it work: https://2019.stateofcss.com/technologies/css-frameworks/#tailwind

I've quickly looked around and it appears this is for all "subpages". In the link above, it's on _"CSS Frameworks"_ under _"Technologies"_. Sharing a result from a "top" page like _"demographics"_ does work.

**Comment by daanhaitsma** [comment]
And on the topic of dead links: The GitHub links on https://2019.stateofcss.com/technologies/methodologies/ also appear to be incorrect

**Comment by SachaG** [comment]
Oh weird, I don't know when that stopped working. Should be good now, thanks!
