### ISSUE TITLE
Features section overview chart

### ISSUE THREAD

**Issue by plouc** [StateOfJS/state-of-css-2019#4]
- Two circle packing charts side by side, one for usage and one for awareness (100% - don't know what it is)

OR

- One chart with concentric circles:

![https://cl.ly/b65a7800714e/Screen%20Shot%202019-05-09%20at%2010.38.36.png](https://cl.ly/b65a7800714e/Screen%20Shot%202019-05-09%20at%2010.38.36.png)

**Comment by SachaG** [comment]
- Two circle packing charts side by side, one for usage and one for awareness (100% - don't know what it is)

**Comment by SachaG** [comment]
WIP

<img width="624" alt="Screen Shot 2019-05-21 at 14 30 50" src="https://user-images.githubusercontent.com/358832/58070708-0d209380-7bd5-11e9-9e57-721b381b4868.png">
