### ISSUE TITLE
Chart for all features page?

### ISSUE THREAD

**Issue by plouc** [StateOfJS/state-of-css-2019#5]
- Use circle packing grouped by feature section
- Use usage as metric
- Add special indicator for high awareness (defined as awareness/(awareness + usage) > 50%)

**Comment by SachaG** [comment]
OR

One chart with concentric circles.

**Comment by SachaG** [comment]
WIP

<img width="1010" alt="Screen Shot 2019-05-21 at 14 30 14" src="https://user-images.githubusercontent.com/358832/58070691-f9752d00-7bd4-11e9-9216-5c0336bf9669.png">
