### ISSUE TITLE
Most requested features numbers

### ISSUE THREAD

**Issue by bkardell** [StateOfJS/state-of-css-2019#53]
Hi I'm trying to read the information presented there.. order and basic proportion matches my intuition and experience but the more concrete numbers I'm having trouble understanding... Thanks for helping me understand better... It seems to suggest that something like container queries is only asked for by like 3%? That can't be a proper reading, I think, right?  Also a few of these things are the same thing? 'parent' and ':has' are the same it seems to me, as would something about subject specifier, I think?  We're they presented as finite choices or user input or..? Finally, the numbers, which include nothing as an option seem to me to not remotely cover something like everyone
.. how?  Sorry, these might seem like silly questions...

**Comment by SachaG** [comment]
Sorry for the late answer! Not everybody filled out that question, which is why it's only 3% of all survey takers. And since this is a freeform field, we do our best to normalize the results but there can be some weirdness sometimes, sorry…
