### ISSUE TITLE
Chart for all tools page?

### ISSUE THREAD

**Issue by plouc** [StateOfJS/state-of-css-2019#6]
- Sunburst chart?

<img width="676" alt="Screen Shot 2019-05-09 at 11 07 32" src="https://user-images.githubusercontent.com/358832/57422360-b7e69880-724a-11e9-8e37-6cbcae356ff0.png">

**Comment by SachaG** [comment]
OR double nested pie chart circle packing:

<img width="513" alt="Screen Shot 2019-05-09 at 11 15 13" src="https://user-images.githubusercontent.com/358832/57422621-d00ae780-724b-11e9-9ae9-7476c9fcef48.png">

**Comment by SachaG** [comment]
WIP:

![Screen Recording 2019-05-21 at 02 08 PM](https://user-images.githubusercontent.com/358832/58070621-badf7280-7bd4-11e9-80f3-f11864b3ffba.gif)

**Comment by SachaG** [comment]
OR: circle packing but with donuts instead of pie charts?

**Comment by SachaG** [comment]
<img width="1136" alt="Screen Shot 2019-05-22 at 10 22 12" src="https://user-images.githubusercontent.com/358832/58141032-c9816480-7c7c-11e9-946d-747493a16803.png">

TODO: 

- add labels to tools
- add labels on path to groups
- add tooltips
- add legend
- rethink colors?
